# This is the Inkpunk community finetune of Stable Diffusion V1.5

- model_id: "inkpunk-diffusion-base"
  model: "Envvi/Inkpunk-Diffusion"

# Create the inpaint mix. This mixes the default SD1.5 inpaint unet with
# the Inkpunk Diffusion unet, giving much better inpaint results.
- model_id: "inkpunk-diffusion-inpaint-unet"
  type: "mix"
  model:
    - "@stable-diffusion-v1-5/inpaint_unet"
    - "@inkpunk-diffusion-base/unet"
  mix:
    type: "difference"
    base: "@stable-diffusion-v1-5/unet"
    alpha: 0

- model_id: "inkpunk-diffusion"
  model: "@inkpunk-diffusion-base"
  overrides:
    inpaint_unet: "@inkpunk-diffusion-inpaint-unet"
    depth_unet: "@stable-diffusion-v2-depth/unet"
    # Inkpunk is a 1.5 finetune, so the default text_encode isn't compatible with the
    # V2 depth unet. We need to override these _just_ for depth
    depth_text_encoder: "@stable-diffusion-v2-depth/text_encoder"
