# This is the Inkpunk community finetune of Stable Diffusion V1.5
- model_id: "inkpunk-diffusion"
  model: "Envvi/Inkpunk-Diffusion"
  overrides:
    depth_unet: "@stable-diffusion-v2-depth/unet"
    inpaint_unet: "@stable-diffusion-v2-inpainting/unet"
    # Inkpunk is a 1.5 finetune, so the default text_encode isn't compatible with the
    # V2 inpaint and depth unets. We need to override these _just_ for depth / inpainting
    depth_text_encoder: "@stable-diffusion-v2-depth/text_encoder"
    inpaint_text_encoder: "@stable-diffusion-v2-inpainting/text_encoder"
