# Abyss Orange Mix 2 - an example of how to load checkpoint / LDM based models

# Orange has a specific VAE for all the models
- model_id: "orange-vae"
  # For any checkpoint, the type should be "ckpt/" followed by the LDM configuration
  type: "ckpt/v1-inference"
  model: "WarriorMama777/OrangeMixs"
  # We're loading a VAE first, which is in a subfolder
  subfolder: "VAEs"
  # Because it's a vae, we need to flag it as such, otherwise we'll get an error when
  # Gyre tries to load a unet and text_encoder too
  whitelist: ["vae"]
  # The Orange VAE will occasionally give black results when running in fp16 mode,
  # so force it to run in fp32 even if Gyre is set to fp16 mode
  fp16: "prevent"

# Now lets load the main checkpoint
- model_id: "orange-abyssmix2-base"
  type: "ckpt/v1-inference"
  model: "WarriorMama777/OrangeMixs"
  subfolder: "Models/AbyssOrangeMix2"
  # There are several .ckpt and .safetensors files in that folder, so we need to
  # explicitly only allow the one we want
  allow_patterns: "AbyssOrangeMix2_sfw.safetensors"
  # Save memory by just loading the model bits that are unique to this model
  whitelist: ["unet", "text_encoder"]

# Now we're going to mix the Abyss Orange Mix 2 unet into the Stable Diffusion V1.5
# inpaint unet to get an Abyss Orange Mix 2 styled inpaint
- model_id: "orange-abyssmix2-inpaint-unet"
  type: "mix"
  model:
    - "@stable-diffusion-v1-5/inpaint_unet"
    - "@orange-abyssmix2-base/unet"
  # Mixing a unet over top of an inpaint_unet only works in difference mode, and
  # both models need to share a common parent to list as the base
  mix:
    type: "difference"
    base: "@stable-diffusion-v1-5/unet"
    alpha: 0

# Lets also mix a text_encoder for use as an inpaint_text_encoder
- model_id: "orange-abyssmix2-inpaint-text_encoder"
  type: "mix"
  model:
    - "@stable-diffusion-v1-5/text_encoder"
    - "@orange-abyssmix2-base/text_encoder"
  mix:
    alpha: 0.5

# Build the complete model
- model_id: "orange-abyssmix2"
  # We base the model on Stable Diffusion V1.5 to share as much as possible
  model: "@stable-diffusion-v1-5"
  overrides:
    # Lots of overrides - mixing in the Abyss Orange Mix 2 base, the Orange VAE
    # and the inpaint_unet and inpaint_text_encoder we just mixed up above
    unet: "@orange-abyssmix2-base/unet"
    text_encoder: "@orange-abyssmix2-base/text_encoder"
    vae: "@orange-vae/vae"
    depth_unet: "@stable-diffusion-v2-depth/unet"
    depth_text_encoder: "@stable-diffusion-v2-depth/text_encoder"
    inpaint_unet: "@orange-abyssmix2-inpaint-unet"
    inpaint_text_encoder: "@orange-abyssmix2-inpaint-text_encoder"
