# The Stable Diffusion V1.5 models from runwayml

- model_id: "stable-diffusion-inpainting"
  # We only use the unet from this model, so only load that. You could also
  # pass a list of submodules here
  whitelist: "unet"
  model: "runwayml/stable-diffusion-inpainting"
  local_model: "./stable-diffusion-inpainting"

- model_id: "stable-diffusion-v1-5"
  # We blacklist the vae as we will be replacing it in the overrides, and this saves a little RAM
  blacklist: "vae"
  model: "runwayml/stable-diffusion-v1-5"
  local_model: "./stable-diffusion-v1-5"
  overrides:
    inpaint_unet: "@stable-diffusion-inpainting/unet"
    vae: "@stability-vae-ema"
