# The Waifu Diffusion V1.4 model, based on Stable Diffusion V2.0

- model_id: "waifu-diffusion-v1-4-base"
  model: "hakurei/waifu-diffusion"
  local_model: "./waifu-diffusion-v1-4"
  # The HuggingFace repo has fp16 weights, but (as of when this comment was written)
  # they're for the older V1.3
  fp16: "local"

- model_id: "waifu-diffusion-v1-4-inpaint-unet"
  type: "mix"
  model:
    - "@stable-diffusion-v2-inpainting/unet"
    - "@waifu-diffusion-v1-4-base/unet"
  mix:
    type: "difference"
    base: "@stable-diffusion-v2-1/unet"
    alpha: 0

- model_id: "waifu-diffusion-v1-4-inpaint-text_encoder"
  type: "mix"
  model:
    - "@stable-diffusion-v2-inpainting/text_encoder"
    - "@waifu-diffusion-v1-4-base/text_encoder"

- model_id: "waifu-diffusion-v1-4"
  model: "@waifu-diffusion-v1-4-base"
  overrides:
    depth_unet: "@stable-diffusion-v2-depth/unet"
    inpaint_unet: "@waifu-diffusion-v1-4-inpaint-unet"
    inpaint_text_encoder: "@waifu-diffusion-v1-4-inpaint-text_encoder"
