- id: "inkpunk-diffusion"
  # To save on initial download time, the Inkpunk Diffusion model is disabled
  # by default. This one should work on any hardware that can run the main model though,
  # so anyone can enable it if they want to.
  enabled: False
  name: "Inkpunk Diffusion"
  description: "Stable Diffusion using the Inkpunk Diffusion model and our Unified pipeline"
  model: "@inkpunk-diffusion"
  options:
    grafted_depth: True
    grafted_inpaint: True
  overrides:
    clip: "@clip-common"
