- id: "inkpunk-diffusion"
  # To save on initial download time, the Inkpunk Diffusion model is disabled by default.
  enabled: False
  name: "Inkpunk Diffusion"
  description: "Inkpunk Diffusion, a painterly inkpunk style finetune based on Stable Diffusion V1.5. Use nvinkpunk in the prompt to strengthen the style."
  model: "@inkpunk-diffusion"
  options:
    grafted_depth: True
    grafted_inpaint: False
  overrides:
    clip: "@clip-common"
