# This is the Abyss Orange Mix 2 model (from a ckpt file)

- id: "orange-abyssmix2"
  # To save on initial download time, the Abyss Orange Mix 2 model is disabled by default.
  enabled: False
  name: "Abyss Orange Mix 2"
  description: "Abyss Orange Mix 2, an anime-style mix based on Stable Diffusion V1.5"
  model: "@orange-abyssmix2"
  options:
    grafted_depth: True
    grafted_inpaint: False
  overrides:
    clip: "@clip-common"
