# This is the standard Waifu Diffusion V1.4 model

- id: "waifu-diffusion-v1-4"
  # To save on initial download time, the Waifu Diffusion model is disabled by default.
  enabled: False
  name: "Waifu Diffusion V1.4"
  description: "Hakurei Waifu Diffusion V1.4, an anime-style finetune based on Stable Diffusion V2"
  model: "@waifu-diffusion-v1-4"
  options:
    grafted_depth: True
    grafted_inpaint: False
  overrides:
    clip: "@clip-common"
