name: gyre
title: Stable Diffusion Image Generation API
http:
  rules:
    - selector: gooseai.EnginesService.ListEngines
      get: "/grpcgateway/engines"
    - selector: gooseai.GenerationService.Generate
      post: "/grpcgateway/generate"
    - selector: gooseai.GenerationService.AsyncGenerate
      post: "/grpcgateway/asyncGenerate"
    - selector: gooseai.GenerationService.AsyncResult
      post: "/grpcgateway/asyncResult"
    - selector: gooseai.GenerationService.AsyncCancel
      post: "/grpcgateway/asyncCancel"
