name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build-cuda118:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
            prefix=cuda118-xformers-,onlatest=true
          images: |
            hafriedlander/gyre
            ghcr.io/stablecabal/gyre
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          target: xformers
          context: .
          file: Dockerfile.cuda118
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            XFORMERS_REPO=https://github.com/hafriedlander/xformers.git
            XFORMERS_REF=53b7454
            TRITON_REF=8650b4d
            DEEPSPEED_REF=tags/v0.7.6
